=== boky01/SubjectParser/src/test/resources/dbUnitXmls/dataSetSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/dataSetSchema" xmlns:tns="http://www.example.org/dataSetSchema"
	elementFormDefault="qualified">

	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:subject" minOccurs="1" maxOccurs="unbounded" />
				<xsd:element ref="tns:specialization" minOccurs="1"
					maxOccurs="unbounded" />
				<xsd:element ref="tns:dependency" minOccurs="1"
					maxOccurs="unbounded" />
				<xsd:element ref="tns:subject_specialization" minOccurs="1"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="subject">
		<xsd:complexType>
			<xsd:attribute name="id" type="xsd:string" use="required"/>
			<xsd:attribute name="credit" type="xsd:string" use="required"/>
			<xsd:attribute name="description" type="xsd:string"
				use="required"/>
			<xsd:attribute name="labor" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="offeredSemester" type="xsd:string"
				use="required"/>
			<xsd:attribute name="practical" type="xsd:string" use="required"/>
			<xsd:attribute name="semesterClosing" type="xsd:string"
				use="required"/>
			<xsd:attribute name="theoretical" type="xsd:string"
				use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="specialization">
		<xsd:complexType>
			<xsd:attribute name="id" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="dependency">
		<xsd:complexType>
			<xsd:attribute name="Id" type="xsd:string" use="required"/>
			<xsd:attribute name="onlyRegistration" type="xsd:string"
				use="required"/>
			<xsd:attribute name="dependencySubject" type="xsd:string"
				use="required"/>
			<xsd:attribute name="specialization_id" type="xsd:string"
				use="required"/>
			<xsd:attribute name="subject_id" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="subject_specialization">
		<xsd:complexType>
			<xsd:attribute name="subject_id" type="xsd:string"
				use="required"/>
			<xsd:attribute name="specialization_id" type="xsd:string"
				use="required"/>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== boky01/SubjectParser/src/test/resources/dbUnitXmls/expectedDataSetWhenDeleteASpecialization.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns="http://www.example.org/dataSetSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.example.org/dataSetSchema dataSetSchema.xsd">
	<subject id="SGYMMET201XXX" credit="1" description="First"
		labor="1" name="Mechanika I. (Statika)" offeredSemester="1" practical="1"
		semesterClosing="1" theoretical="1" />
	<subject id="SGYMMET202XXX" credit="2" description="Second"
		labor="2" name="Mechanika II. (Szilárdságtan)" offeredSemester="2"
		practical="2" semesterClosing="2" theoretical="2" />
	<subject id="SGYMMET203XXX" credit="3" description="Third"
		labor="3" name="Mechanika III. (Tartók statikája)" offeredSemester="3"
		practical="3" semesterClosing="0" theoretical="3" />
	<subject id="SGYMMET205XXX" credit="4" description="Forth"
		labor="4" name="Vasbeton szerkezetek I." offeredSemester="4"
		practical="4" semesterClosing="0" theoretical="4" />
	<subject id="SGYMMET206XXX" credit="5" description="Fifth"
		labor="5" name="Fa- és acélszerkezetek I." offeredSemester="5"
		practical="5" semesterClosing="2" theoretical="5" />
	<subject id="SGYMTUB2317XA" credit="6" description="Sixth"
		labor="6" name="A katasztrófavédelem alapjai" offeredSemester="6"
		practical="6" semesterClosing="1" theoretical="6" />

	<specialization id="GEOTECHNIKAI" name="Geotechnikai" />
<!-- 	<specialization id="KOTELEZO" name="Kötelező"/> -->
	<specialization id="MAGASEPITESI" name="Magasépítési" />
	<specialization id="TELEPULESI" name="Települési" />
	<specialization id="TUZVEDELMI" name="Tűz- és katasztrófavédelmi" />
	<specialization id="VALASZTHATO" name="Szabadon választható" />


	<!-- <dependency Id="1" onlyRegistration="0" dependencySubject="SGYMMET201XXX" -->
	<!-- specialization_id="KOTELEZO" subject_id="SGYMMET202XXX" /> -->
	<!-- <dependency Id="2" onlyRegistration="0" dependencySubject="SGYMMET202XXX" -->
	<!-- specialization_id="KOTELEZO" subject_id="SGYMMET203XXX" /> -->
	<!-- <dependency Id="3" onlyRegistration="0" dependencySubject="SGYMMET203XXX" -->
	<!-- specialization_id="KOTELEZO" subject_id="SGYMMET205XXX" /> -->
	<!-- <dependency Id="4" onlyRegistration="0" dependencySubject="SGYMMET203XXX" -->
	<!-- specialization_id="KOTELEZO" subject_id="SGYMMET206XXX" /> -->
	<!-- <dependency Id="5" onlyRegistration="1" dependencySubject="SGYMTUB2317XA" -->
	<!-- specialization_id="KOTELEZO" subject_id="SGYMMET206XXX" /> -->
	<dependency Id="6" onlyRegistration="1" dependencySubject="SGYMTUB2317XA"
		specialization_id="MAGASEPITESI" subject_id="SGYMMET206XXX" />


<subject_specialization subject_id="SGYMMET206XXX"
		specialization_id="GEOTECHNIKAI" />
	<subject_specialization subject_id="SGYMTUB2317XA"
		specialization_id="GEOTECHNIKAI" />
<!-- 	<subject_specialization subject_id="SGYMMET201XXX" -->
<!-- 		specialization_id="KOTELEZO" /> -->
<!-- 	<subject_specialization subject_id="SGYMMET202XXX" -->
<!-- 		specialization_id="KOTELEZO" /> -->
<!-- 	<subject_specialization subject_id="SGYMMET203XXX" -->
<!-- 		specialization_id="KOTELEZO" /> -->
<!-- 	<subject_specialization subject_id="SGYMMET205XXX" -->
<!-- 		specialization_id="KOTELEZO" /> -->
<!-- 	<subject_specialization subject_id="SGYMMET206XXX" -->
<!-- 		specialization_id="KOTELEZO" /> -->
	<subject_specialization subject_id="SGYMTUB2317XA"
		specialization_id="MAGASEPITESI" />
	<subject_specialization subject_id="SGYMTUB2317XA"
		specialization_id="TELEPULESI" />
</dataset>
